name: Luagin
version: '2.4.1'
main: tech.ezeny.luagin.Luagin
api-version: '1.21'
authors: [Ezeny]
description: Run Minecraft plugins using Lua scripting

commands:
  luagin:
    description: Luagin 插件命令
    usage: /luagin <reload|help> [脚本名]
    permission: luagin.admin
    aliases: [lk]
permissions:
  luagin.admin:
    description: 允许使用 Luagin 管理命令
    default: op